### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by jfix** [mereth/git-ant-tasks#1]
Hello, great project! :-) It would be nice if the git tasks take into consideration a proxy property that would allow to interact with git repositories _via_ company firewalls and _what-have-you_. Merci, à bientôt !

**Comment by mereth** [comment]
Hi, you should be able to use those tasks through a proxy with the [setproxy](https://ant.apache.org/manual/Tasks/setproxy.html) task.

`<setproxy proxyhost="wsg-proxy.domain.org"/>`
`<gitclone repo="${repo}" uri="${remote}" branch="master"/>`

M'AB

**Comment by jfix** [comment]
I confirm that this works _beautifully_! 

Thanks, see you soon!
